---
- name: clone and package project "boxfuse-sample-java-war-hello"
  hosts: build
  become: no

  tasks:
  - name: git clone project
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /usr/src/boxfuse
      clone: yes

  - name: Running mvn clean
    shell: "cd /usr/src/boxfuse/ &&  mvn clean install"
    become: yes
    register: mvn_result

  - name: "mvn clean task output"
    debug:
     var: mvn_result

  - name: get .war-file from bulid-machine to master-machine
    fetch:
      src: //usr/src/boxfuse/*.war
      dest: /usr/bin/boxfuse
